[package]
name = "nft"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
solana-program-test = "=1.11.7"
solana-sdk = "=1.11.7"
solana-client = "=1.11.7"
spl-token = "=3.5.0"
spl-associated-token-account = "=1.1.1"
mpl-token-metadata = "=1.3.4"
borsh = "=0.9.3"